### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by kerwinxu** [nicedayzhu/netAssist#1]
python main.py
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in "D:\Qt\6.2.1\msvc2019_64\plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

出现这个错误后，我搜索了一下，我设置QT_QPA_PLATFORM_PLUGIN_PATH 环境变量为
D:\Qt\6.2.1\msvc2019_64\plugins
D:\anaconda3\Lib\site-packages\PyQt5\Qt\plugins
我设置了2次，都不可以。

**Comment by nicedayzhu** [comment]
推荐clone master分支的代码，使用pycharm进行开发。这个项目是python3版本的，应该跟你的msvc2019_64没有关系。所以请检查一下开发环境。可以尝试用conda新建一个env，然后在此env中安装相关module来测试

**Comment by kerwinxu** [comment]
> 

谢谢，已经解决，方法是设置环境变量 QT_QPA_PLATFORM_PLUGIN_PATH  为 D:\anaconda3\Library\plugins\platforms 。
