### ISSUE TITLE
十六进制发送不支持超过7F

### ISSUE THREAD

**Issue by Megumism** [nicedayzhu/netAssist#2]
我下载的是release里的exe，虽然不知道您是否还维护这个项目，但我觉得至少十六进制发送还是要支持一下00~FF的

**Comment by nicedayzhu** [comment]
有相关截图吗？我测试没有问题
![RS~SVJ6Y()%LGI96IC42)US](https://user-images.githubusercontent.com/5286862/168483368-da4ec457-8213-4346-a950-03481888e6aa.png)

**Comment by Megumism** [comment]
好的我明白问题所在了，我没有把接受设为16进制显示，非常感谢
